server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /jialegou
    username: jialegou
    password: jialegou
    host: 192.168.43.219
jialegou:
  sms:
    accessKeyId:
    accessKeySecret:
    signName: hilkr
    verifyCodeTemplate: SMS_164507246