server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /jialegou
    username: jialegou
    password: jialegou
    host: 192.168.43.219
jialegou:
  sms:
    accessKeyId: LTAIKcIj7vazhc5U
    accessKeySecret: Vlv5JTjfJQehGTrZDdiyg7akZMljbv
    signName: hilkr
    verifyCodeTemplate: SMS_164507246