server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
jialegou:
  jwt:
    secret: ly@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    pubKeyPath: /Users/sam/Documents/Developer/swe15086/jialegou/jialegou-auth/src/main/resources/key/id_rsa.pub # 公钥地址 TODO
    priKeyPath: /Users/sam/Documents/Developer/swe15086/jialegou/jialegou-auth/src/main/resources/key/id_rsa.pri # 私钥地址 TODO
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 1800