server:
  port: 8081 # 端口
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/jialegou
    username: tester
    password: lkr.7664
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    com:
      hilkr: debug