server:
  port: 8085
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/jialegou
    username: tester
    password: lkr.7664
  redis:
    host: 192.168.43.219
  rabbitmq:
    username: jialegou
    password: jialegou
    virtual-host: /jialegou
    host: 192.168.43.219
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  type-aliases-package: com.hilkr.users.dto