server:
  port: 8085
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/jialegou
    username: tester
    password: lkr.7664
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  redis:
    host: 192.168.43.219
  rabbitmq:
    username: jialegou
    password: jialegou
    virtual-host: /jialegou
    host: 192.168.43.219
    template:
      retry:
        enabled: true
        max-interval: 210000ms
        initial-interval: 10000ms
        multiplier: 2
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
mybatis-plus:
  typeAliasesPackage: com.hilkr
  mapper-locations: classpath:/com/hilkr/dal/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#mybatis
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.baomidou.springboot.entity
#  typeEnumsPackage: com.baomidou.springboot.entity.enums
#  global-config:
#    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 2
#    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
#    #驼峰下划线转换
#    db-column-underline: true
#    #刷新mapper 调试神器
#    refresh-mapper: true
#    #数据库大写下划线转换
#    #capital-mode: true
#    #序列接口实现类配置
#    #key-generator: com.baomidou.springboot.xxx
#    #逻辑删除配置
#    logic-delete-value: 0
#    logic-not-delete-value: 1
#    #自定义填充策略接口实现
#    #meta-object-handler: com.baomidou.springboot.xxx
#    #自定义SQL注入器
#    #sql-injector: com.baomidou.springboot.xxx
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false